<?php
class AE_PaypalExpress
{
    
    public $_test_mod;
    public $_type;
    
    //protected $_order;
    
    
    /**
     * API_Signature:The Signature associated with the API user. which is generated by paypal.
     */
    public $_api_signature;
    
    /**
     * API user: The user that is identified as making the call. you can
     * also use your own API username that you created on PayPal?s sandbox
     * or the PayPal live site
     */
    public $_api_username;
    
    /**
     * API_password: The password associated with the API user
     * If you are using your own API username, enter the API password that
     * was generated by PayPal below
     * IMPORTANT - HAVING YOUR API PASSWORD INCLUDED IN THE MANNER IS NOT
     * SECURE, AND ITS ONLY BEING SHOWN THIS WAY FOR TESTING PURPOSES
     */
    public $_api_password;
    
    /**
     * Endpoint: this is the server URL which you have to connect for submitting your API request.
     */
    public $_api_endpoint;
    
    /**
     * Version: this is the API version in the request.
     * It is a mandatory parameter for each API request.
     * The only supported value at this time is 2.3
     */
    public $_version;
    
    /*
    PayPal URL. This is the URL that the buyer is
       first sent to to authorize payment with their paypal account
      change the URL depending if you are testing on the sandbox
      or going to the live PayPal site
      For the sandbox, the URL is
      https://www.sandbox.paypal.com/webscr&cmd=_express-checkout&token=
      For the live site, the URL is
      https://www.paypal.com/webscr&cmd=_express-checkout&token=
    */
    public $_paypal_url;
    public $_dg_url;
    public $_proxy;
    public $_proxy_host;
    public $_proxy_port;
    public static $instance = false;
    
    function __construct($mode = false) {
        
        $api = self::get_api();
        
        extract($api);
        
        // init api setting
        $this->_api_username = trim($username);
        $this->_api_password = trim($password);
        $this->_api_signature = trim($signature);
        
        $this->_api_endpoint = 'https://api-3t.sandbox.paypal.com/nvp';
        $this->_version = 87.0;
        
        $this->_proxy = false;
        $this->_test_mod = ae_get_option('test_mode', false);
        
        if ($this->_test_mod) {
            $this->_api_endpoint = "https://api-3t.sandbox.paypal.com/nvp";
            $this->_paypal_url = "https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=";
            $this->_dg_url = "https://www.sandbox.paypal.com/incontext?token=";
        } else {
            $this->_api_endpoint = "https://api-3t.paypal.com/nvp";
            $this->_paypal_url = "https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=";
            $this->_dg_url = "https://www.paypal.com/incontext?token=";
        }
    }
    public static function getInstance() {
        if (!self::$instance) {
        	self::$instance = new AE_PaypalExpress();
        }
        return self::$instance;
    }
    
    function nvp_header() {
        
        $API_Endpoint = $this->_api_endpoint;
        $API_UserName = $this->_api_username;
        $API_Password = $this->_api_password;
        $API_Signature = $this->_api_signature;
        $nvp_Header = '';
        $subject = '';
        $AUTH_token = '';
        $AUTH_signature = '';
        $AUTH_timestamp = '';
        $version = $this->_version;
        
        $nvpHeaderStr = "";
        
        if (defined('AUTH_MODE')) {
            
            //$AuthMode = "3TOKEN"; //Merchant's API 3-TOKEN Credential is required to make API Call.
            //$AuthMode = "FIRSTPARTY"; //Only merchant Email is required to make EC Calls.
            //$AuthMode = "THIRDPARTY";Partner's API Credential and Merchant Email as Subject are required.
            $AuthMode = "AUTH_MODE";
        } else {
            
            if ((!empty($API_UserName)) && (!empty($API_Password)) && (!empty($API_Signature)) && (!empty($subject))) {
                $AuthMode = "THIRDPARTY";
            } else if ((!empty($API_UserName)) && (!empty($API_Password)) && (!empty($API_Signature))) {
                $AuthMode = "3TOKEN";
            } elseif (!empty($AUTH_token) && !empty($AUTH_signature) && !empty($AUTH_timestamp)) {
                $AuthMode = "PERMISSION";
            } elseif (!empty($subject)) {
                $AuthMode = "FIRSTPARTY";
            }
        }
        switch ($AuthMode) {
            case "3TOKEN":
                $nvpHeaderStr = "&PWD=" . urlencode($API_Password) . "&USER=" . urlencode($API_UserName) . "&SIGNATURE=" . urlencode($API_Signature);
                break;

            case "FIRSTPARTY":
                $nvpHeaderStr = "&SUBJECT=" . urlencode($subject);
                break;

            case "THIRDPARTY":
                $nvpHeaderStr = "&PWD=" . urlencode($API_Password) . "&USER=" . urlencode($API_UserName) . "&SIGNATURE=" . urlencode($API_Signature) . "&SUBJECT=" . urlencode($subject);
                break;

            case "PERMISSION":
                $nvpHeaderStr = formAutorization($AUTH_token, $AUTH_signature, $AUTH_timestamp);
                break;
        }
        return $nvpHeaderStr;
    }
    
    /**
     * hash_call: Function to perform the API call to PayPal using API signature
     * @methodName is name of API  method.
     * @nvpStr is nvp string.
     * returns an associtive array containing the response from the server.
     */
    function hash_call($methodName, $nvpStr) {
        
        //declaring of global variables
        $API_Endpoint = $this->_api_endpoint;
        $API_UserName = $this->_api_username;
        $API_Password = $this->_api_password;
        $API_Signature = $this->_api_signature;
        $version = $this->_version;
        $USE_PROXY = false;
        $PROXY_HOST = $this->_proxy_host;
        $PROXY_PORT = $this->_proxy_port;
        
        $sBNCode = "PP-ECWizard";
        
        //setting the curl parameters.
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $API_Endpoint);
        curl_setopt($ch, CURLOPT_VERBOSE, 1);
        
        //turning off the server and peer verification(TrustManager Concept).
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
        
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        
        //if USE_PROXY constant set to TRUE in Constants.php, then only proxy will be enabled.
        //Set proxy name to PROXY_HOST and port number to PROXY_PORT in constants.php
        if ($USE_PROXY) curl_setopt($ch, CURLOPT_PROXY, $PROXY_HOST . ":" . $PROXY_PORT);
        
        //NVPRequest for submitting to server
        $nvpreq = "METHOD=" . urlencode($methodName) . "&VERSION=" . urlencode($version) . "&PWD=" . urlencode($API_Password) . "&USER=" . urlencode($API_UserName) . "&SIGNATURE=" . urlencode($API_Signature) . $nvpStr . "&BUTTONSOURCE=" . urlencode($sBNCode);
        
        //setting the nvpreq as POST FIELD to curl
        curl_setopt($ch, CURLOPT_POSTFIELDS, $nvpreq);
        
        //getting response from server
        $response = curl_exec($ch);
        
        //convrting NVPResponse to an Associative Array
        $nvpResArray = $this->deformatNVP($response);
        $nvpReqArray = $this->deformatNVP($nvpreq);
        $_SESSION['nvpReqArray'] = $nvpReqArray;
        
        if (curl_errno($ch)) {
            
            // moving to display page to display curl errors
            $_SESSION['curl_error_no'] = curl_errno($ch);
            $_SESSION['curl_error_msg'] = curl_error($ch);
            
            //Execute the Error handling module to display errors.
            
        } else {
            
            //closing the curl
            curl_close($ch);
        }
        
        return $nvpResArray;
    }
    
    /** 
     * This function will take NVPString and convert it to an Associative Array and it will decode the response.
     * It is usefull to search for a particular key and displaying arrays.
     * @nvpstr is NVPString.
     * @nvpArray is Associative Array.
     */
    
    function deformatNVP($nvpstr) {
        $intial = 0;
        $nvpArray = array();
        
        while (strlen($nvpstr)) {
            
            //postion of Key
            $keypos = strpos($nvpstr, '=');
            
            //position of value
            $valuepos = strpos($nvpstr, '&') ? strpos($nvpstr, '&') : strlen($nvpstr);
            
            /*getting the Key and Value values and storing in a Associative Array*/
            $keyval = substr($nvpstr, $intial, $keypos);
            $valval = substr($nvpstr, $keypos + 1, $valuepos - $keypos - 1);
            
            //decoding the respose
            $nvpArray[urldecode($keyval) ] = urldecode($valval);
            $nvpstr = substr($nvpstr, $valuepos + 1, strlen($nvpstr));
        }
        
        return $nvpArray;
    }
    
    function form_autorization($auth_token, $auth_signature, $auth_timestamp) {
        
        $authString = "token=" . $auth_token . ",signature=" . $auth_signature . ",timestamp=" . $auth_timestamp;
        return $authString;
    }
    
    /**
     * save paypal setting
     * @param $settings : array ()
     * 	- cmd   : kind of ET_Payment button
     *  - charset : setting character set
     *  - total : amount
     *  - submit : submit button text
     *  - form  :
     *  - cbt :
     *  - ipn : notify check
     *  - currency
     *  - return : url is redirected after ET_Payment succesful
     *  - notify_url : url will be redirected if have notification
     *  - cancel_return : url will be redirected when buyer cancel ET_Payment
     *  - test_mod : test mod for developer test with sanbox account
     *  - test_mail : mail address receives notify email in test mod
     * @see ET_Payment::set_settings()
     */
    
    /*
    function set_settings( $settings = array () ) {
    
    }
    */
    
    /**
     * @return settings array
     * @see ET_Payment::get_settings()
     */
    function get_settings() {
        return $this->_settings;
    }
    
    /**
     * get paypal checkout url
     * return string : url
     */
    function get_paypal_url() {
        return $this->_paypal_url;
    }
    
    static function get_api() {
        return ae_get_option('ppdigital', array(
            'api_username' => '',
            'api_password' => '',
            'api_signature' => ''
        ));
    }
    
    // function accept visitor
    function accept(ET_PaymentVisitor $visitor) {
        $visitor->visitPaypal($this);
    }
    
    public function is_enable() {
        
        if ($this->_api_username && $this->_api_password && $this->_api_signature) return true;
        return false;
    }
    
    function RedirectToPayPalDG($token) {
        
        // Redirect to paypal.com here
        $payPalURL = $this->_dg_url . $token;
        header("Location: " . $payPalURL);
        exit;
    }
}

class AE_PPExpressVisitor
{
 	public $payment;
 	function __construct(){
 		$this->payment = new AE_PaypalExpress(ET_Payment::get_payment_test_mode());
 	}
    /*
    '-------------------------------------------------------------------------------------------------------------------------------------------
    ' Purpose: 	Prepares the parameters for the SetExpressCheckout API Call for a Digital Goods payment.
    ' Inputs:
    '		paymentAmount:  	Total value of the shopping cart
    '		currencyCodeType: 	Currency code value the PayPal API
    '		paymentType: 		paymentType has to be one of the following values: Sale or Order or Authorization
    '		returnURL:			the page where buyers return to after they are done with the payment review on PayPal
    '		cancelURL:			the page where buyers return to when they cancel the payment review on PayPal
    '--------------------------------------------------------------------------------------------------------------------------------------------
    */
    function SetExpressCheckoutDG($order) {
        
        //------------------------------------------------------------------------------------------------------------------------------------
        // Construct the parameter string that describes the SetExpressCheckout API call in the shortcut implementatio
        
        $payment = $this->payment;
        
        $paymentType = 'sale';
        $paymentAmount = $order['total'];
        $currencyCodeType = $order['currencyCodeType'];
        
        $returnURL = et_get_page_link('process-payment', array(
            'paymentType' => 'ppdigital'
        ));
        $cancelURL = et_get_page_link('process-payment', array(
            'paymentType' => 'ppdigital'
        ));
        
        $products = $order['products'];
        
        if ($order['total'] < $order['total_before_discount']) {
            $products[] = array(
                'NAME' => __("Discount", ET_DOMAIN) ,
                'QTY' => '1',
                'AMT' => ($order['total'] - $order['total_before_discount'])
            );
        }
        
        $nvpstr = "&PAYMENTREQUEST_0_AMT=" . $paymentAmount;
        $nvpstr.= "&PAYMENTREQUEST_0_PAYMENTACTION=" . $paymentType;
        $nvpstr.= "&RETURNURL=" . $returnURL;
        $nvpstr.= "&CANCELURL=" . $cancelURL;
        $nvpstr.= "&PAYMENTREQUEST_0_CURRENCYCODE=" . $currencyCodeType;
        $nvpstr.= "&REQCONFIRMSHIPPING=0";
        $nvpstr.= "&NOSHIPPING=1";
        
        $index = 0;
        foreach ($products as $key => $item) {
            
            $nvpstr.= "&L_PAYMENTREQUEST_0_NAME" . $index . "=" . urlencode($item["NAME"]);
            $nvpstr.= "&L_PAYMENTREQUEST_0_AMT" . $index . "=" . urlencode($item['AMT']);
            $nvpstr.= "&L_PAYMENTREQUEST_0_QTY" . $index . "=" . urlencode($item["QTY"]);
            $nvpstr.= "&L_PAYMENTREQUEST_0_ITEMCATEGORY" . $index . "=Digital";
            $index++;
        }
        
        //'---------------------------------------------------------------------------------------------------------------
        //' Make the API call to PayPal
        //' If the API call succeded, then redirect the buyer to PayPal to begin to authorize payment.
        //' If an error occured, show the resulting errors
        //'---------------------------------------------------------------------------------------------------------------
        $resArray = $payment->hash_call("SetExpressCheckout", $nvpstr);
        $ack = strtoupper($resArray["ACK"]);
        if ($ack == "SUCCESS" || $ack == "SUCCESSWITHWARNING") {
            $token = urldecode($resArray["TOKEN"]);
            $_SESSION['TOKEN'] = $token;
            
            //$payment->RedirectToPayPalDG ($token);
            
        }
        
        return $resArray;
    }
    
    /*
    '-------------------------------------------------------------------------------------------------------------------------------------------
    ' Purpose: 	Prepares the parameters for the GetExpressCheckoutDetails API Call.
    '
    ' Inputs:
    '		sBNCode:	The BN code used by PayPal to track the transactions from a given shopping cart.
    ' Returns:
    '		The NVP Collection object of the GetExpressCheckoutDetails Call Response.
    '--------------------------------------------------------------------------------------------------------------------------------------------
    */
    function ConfirmPayment($token, $payerID, $order) {
        
        /* Gather the information to make the final call to
        finalize the PayPal payment.  The variable nvpstr
        holds the name value pairs
        */
        
        $token = urlencode($token);
        $payment = $this->payment;
        
        $paymentType = urlencode('sale');
        $currencyCodeType = urlencode($order['currencyCodeType']);
        $FinalPaymentAmt = $order['total'];
        
        $procducts = $order['products'];
        
        $product = get_post_meta($order['ID'], 'et_order_products', true);
        
        $payerID = urlencode($payerID);
        $serverName = urlencode($_SERVER['SERVER_NAME']);
        
        $nvpstr = '&TOKEN=' . $token . '&PAYERID=' . $payerID . '&PAYMENTREQUEST_0_PAYMENTACTION=' . $paymentType . '&PAYMENTREQUEST_0_AMT=' . $FinalPaymentAmt;
        $nvpstr.= '&PAYMENTREQUEST_0_CURRENCYCODE=' . $currencyCodeType . '&IPADDRESS=' . $serverName;
        
        $index = 0;
        foreach ($procducts as $key => $item) {
            
            $nvpstr.= "&L_PAYMENTREQUEST_0_NAME" . $index . "=" . urlencode($item["NAME"]);
            $nvpstr.= "&L_PAYMENTREQUEST_0_AMT" . $index . "=" . urlencode($order['total']);
            $nvpstr.= "&L_PAYMENTREQUEST_0_QTY" . $index . "=" . urlencode($item["QTY"]);
            $nvpstr.= "&L_PAYMENTREQUEST_0_ITEMCATEGORY" . $index . "=Digital";
            $index++;
        }
        
        /* Make the call to PayPal to finalize payment
        If an error occured, show the resulting errors
        */
        $resArray = $payment->hash_call("DoExpressCheckoutPayment", $nvpstr);
        
        /* Display the API response back to the browser.
        If the response from PayPal was a success, display the response parameters'
        If the response was an error, display the errors received using APIError.php.
        */
        $ack = strtoupper($resArray["ACK"]);
        
        return $resArray;
    }
}
